/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_TestJni */

#ifndef _Included_jni_TestJni
#define _Included_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_TestJni
 * Method:    display
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_TestJni_display
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
